import mongoose from "mongoose";

export const creatorId = new mongoose.Types.ObjectId(
    "6408e87d7663c77ffe4a01c9"
);

export const recipes = [
    {
        title: "Spaghetti with Meat Sauce",
        description:
            "A classic Italian dish made with pasta and a hearty meat sauce.",
        estimateTime: 45,
        servings: 4,
        steps: "1. Cook spaghetti according to package directions. \n2. In a large skillet, cook beef over medium heat until no longer pink; drain. \n3. Add onion and garlic to the skillet and cook until tender. \n4. Stir in the crushed tomatoes, tomato paste, water, sugar, basil, fennel seed, Italian seasoning, salt, and pepper. \n5. Bring to a boil, then reduce heat and simmer for 30 minutes. \n6. Serve sauce over spaghetti.",
        tips: "For a vegetarian option, you can substitute the beef with chopped mushrooms. You can also add grated Parmesan cheese on top of the pasta for extra flavor.",
        ingredients: [
            { name: "spaghetti", amount: 1, unit: "pound" },
            { name: "ground beef", amount: 1, unit: "pound" },
            { name: "onion", amount: 1, unit: "" },
            { name: "garlic", amount: 2, unit: "cloves" },
            { name: "crushed tomatoes", amount: 28, unit: "ounces" },
            { name: "tomato paste", amount: 6, unit: "ounces" },
            { name: "water", amount: 1 / 2, unit: "cup" },
            { name: "sugar", amount: 1, unit: "teaspoon" },
            { name: "dried basil", amount: 1, unit: "teaspoon" },
            { name: "fennel seed", amount: 1 / 2, unit: "teaspoon" },
            { name: "Italian seasoning", amount: 1, unit: "teaspoon" },
            { name: "salt", amount: 1 / 2, unit: "teaspoon" },
            { name: "black pepper", amount: 1 / 4, unit: "teaspoon" },
        ],
        photo: "https://res.cloudinary.com/dfjboi5a7/image/upload/v1678652889/pyq2vicfdcmstrccdgxo.jpg",
        creator: creatorId,
    },
    {
        title: "Classic Lasagna",
        description:
            "Layers of pasta, meat sauce, and cheese make this Italian dish a family favorite.",
        estimateTime: 90,
        servings: 8,
        steps: "1. Cook lasagna noodles according to package directions. \n2. In a large skillet, cook ground beef over medium heat until no longer pink; drain. \n3. Add onion and garlic to the skillet and cook until tender. \n4. Stir in the crushed tomatoes, tomato paste, water, sugar, basil, oregano, salt, and pepper. \n5. Bring to a boil, then reduce heat and simmer for 30 minutes. \n6. In a separate bowl, mix together ricotta cheese, egg, parsley, and salt. \n7. Preheat oven to 375 degrees F (190 degrees C). \n8. Spread a layer of meat sauce on the bottom of a 9x13 inch baking dish. \n9. Arrange a single layer of noodles on top of the meat sauce. \n10. Spread a layer of the ricotta mixture over the noodles. \n11. Sprinkle a layer of mozzarella cheese on top of the ricotta mixture. \n12. Repeat layers until all ingredients are used, ending with a layer of mozzarella cheese on top. \n13. Cover with aluminum foil and bake for 25 minutes. \n14. Remove foil and bake for an additional 25 minutes until cheese is golden brown and bubbly. \n15. Let cool for 10 minutes before slicing and serving.",
        tips: "Make sure to let the lasagna cool for a bit before serving so it can set up and hold its shape. You can also add sautéed mushrooms, zucchini, or bell peppers to the meat sauce for added flavor.",
        ingredients: [
            { name: "lasagna noodles", amount: 12, unit: "ounces" },
            { name: "ground beef", amount: 1, unit: "pound" },
            { name: "onion", amount: 1, unit: "" },
            { name: "garlic", amount: 2, unit: "cloves" },
            { name: "crushed tomatoes", amount: 28, unit: "ounces" },
            { name: "tomato paste", amount: 6, unit: "ounces" },
            { name: "water", amount: 1 / 2, unit: "cup" },
            { name: "sugar", amount: 1, unit: "teaspoon" },
            { name: "dried basil", amount: 1, unit: "teaspoon" },
            { name: "dried oregano", amount: 1, unit: "teaspoon" },
            { name: "salt", amount: 1 / 2, unit: "teaspoon" },
            { name: "black pepper", amount: 1 / 4, unit: "teaspoon" },
            { name: "ricotta cheese", amount: 15, unit: "ounces" },
            { name: "egg", amount: 1, unit: "" },
            { name: "parsley", amount: 1 / 4, unit: "cup" },
            { name: "shredded mozzarella cheese", amount: 2, unit: "cups" },
        ],
        photo: "https://res.cloudinary.com/dfjboi5a7/image/upload/v1678652910/uapwukeg0ztfxikkvmhg.jpg",
        creator: creatorId,
    },
    {
        title: "Chicken Tikka Masala",
        description:
            "A classic Indian dish made with marinated chicken cooked in a creamy tomato-based sauce.",
        estimateTime: 60,
        servings: 4,
        steps: "1. In a large bowl, mix together yogurt, lemon juice, cumin, cinnamon, cayenne pepper, black pepper, ginger, and salt. \n2. Add chicken to the bowl and toss to coat. Cover and marinate in the refrigerator for at least 1 hour. \n3. Preheat the oven to 400°F. \n4. Thread marinated chicken onto skewers and place on a baking sheet. \n5. Bake in preheated oven until chicken is no longer pink, about 20 minutes. \n6. In a large saucepan, heat oil over medium heat. \n7. Add onion and garlic and cook until tender. \n8. Stir in tomato sauce, cream, paprika, garam masala, salt, and cayenne pepper. \n9. Bring to a boil, then reduce heat and simmer for 20-30 minutes. \n10. Add cooked chicken to the sauce and let it simmer for 5-10 minutes. \n11. Serve hot over rice or with naan bread.",
        tips: "For a vegetarian option, you can substitute the chicken with paneer cheese. You can also add chopped cilantro on top of the dish for extra flavor.",
        ingredients: [
            { name: "yogurt", amount: 1, unit: "cup" },
            { name: "lemon juice", amount: 1, unit: "tablespoon" },
            { name: "ground cumin", amount: 1, unit: "teaspoon" },
            { name: "ground cinnamon", amount: 1, unit: "teaspoon" },
            { name: "cayenne pepper", amount: 1 / 2, unit: "teaspoon" },
            { name: "ground black pepper", amount: 1 / 2, unit: "teaspoon" },
            { name: "fresh ginger", amount: 2, unit: "tablespoons" },
            { name: "salt", amount: 1 / 2, unit: "teaspoon" },
            { name: "chicken breasts", amount: 4, unit: "" },
            { name: "vegetable oil", amount: 2, unit: "tablespoons" },
            { name: "onion", amount: 1, unit: "" },
            { name: "garlic", amount: 3, unit: "cloves" },
            { name: "tomato sauce", amount: 15, unit: "ounces" },
            { name: "heavy cream", amount: 1 / 2, unit: "cup" },
            { name: "paprika", amount: 1, unit: "teaspoon" },
            { name: "garam masala", amount: 1, unit: "teaspoon" },
            { name: "cayenne pepper", amount: 1 / 4, unit: "teaspoon" },
        ],
        photo: "https://res.cloudinary.com/dfjboi5a7/image/upload/v1678652873/qlelebtjvoqjrodvj4wb.jpg",
        creator: creatorId,
    },
    {
        title: "Pad Thai",
        description:
            "A classic Thai stir-fry dish made with rice noodles, peanuts, and vegetables.",
        estimateTime: 30,
        servings: 4,
        steps: "1. Soak rice noodles in warm water for 15-20 minutes until soft, then drain.\n2. In a wok or large skillet, heat oil over medium-high heat. Add garlic and sauté until fragrant, then add shrimp and cook until pink. \n3. Add tofu, bean sprouts, and scallions to the skillet and stir-fry for 1-2 minutes. \n4. Push the vegetables and shrimp to the side of the skillet and add beaten eggs to the center. Scramble the eggs until cooked, then mix with the vegetables and shrimp. \n5. Add the drained noodles to the skillet and stir-fry for 1-2 minutes. \n6. Add tamarind paste, fish sauce, sugar, and chili powder to the skillet and stir to combine. \n7. Serve hot, garnished with peanuts and lime wedges.",
        tips: "If you don't have tamarind paste, you can use lime juice instead. You can also add chicken or beef instead of shrimp.",
        ingredients: [
            { name: "rice noodles", amount: 8, unit: "ounces" },
            { name: "peanut oil", amount: 3, unit: "tablespoons" },
            { name: "garlic", amount: 2, unit: "cloves" },
            { name: "shrimp", amount: 1 / 2, unit: "pound" },
            { name: "firm tofu", amount: 6, unit: "ounces" },
            { name: "bean sprouts", amount: 1 / 2, unit: "cup" },
            { name: "scallions", amount: 3, unit: "" },
            { name: "eggs", amount: 2, unit: "" },
            { name: "tamarind paste", amount: 2, unit: "tablespoons" },
            { name: "fish sauce", amount: 2, unit: "tablespoons" },
            { name: "sugar", amount: 2, unit: "tablespoons" },
            { name: "chili powder", amount: 1 / 4, unit: "teaspoon" },
            { name: "peanuts", amount: 1 / 4, unit: "cup" },
            { name: "lime wedges", amount: 4, unit: "" },
        ],
        photo: "https://res.cloudinary.com/dfjboi5a7/image/upload/v1678652923/mjsvulvkzvyp6mvsp9lf.jpg",
        creator: creatorId,
    },
    {
        title: "Tonkatsu Ramen",
        description:
            "A hearty and satisfying Japanese dish that features noodles in a flavorful pork broth, topped with crispy breaded pork.",
        estimateTime: 60,
        servings: 4,
        steps: "1. Cook ramen noodles according to package directions. \n2. In a separate pot, bring chicken broth to a simmer. Add in grated ginger, soy sauce, and mirin. Let simmer for 10 minutes. \n3. In a small bowl, mix together cornstarch and water to create a slurry. Add the slurry to the pot and whisk to combine. Let simmer for another 5 minutes. \n4. While the broth is simmering, season the pork cutlets with salt and pepper. Coat in flour, dip in beaten egg, and coat in panko breadcrumbs. \n5. In a large skillet, heat vegetable oil over medium-high heat. Fry the pork cutlets until golden brown on both sides. \n6. To serve, divide the cooked ramen noodles into bowls. Pour the hot broth over the noodles and top with the breaded pork, sliced green onions, and sliced boiled egg.",
        tips: "To make the broth even richer, you can simmer pork bones along with the chicken broth. You can also customize the toppings to your liking - try adding bamboo shoots, nori, or sliced mushrooms.",
        ingredients: [
            { name: "ramen noodles", amount: 4, unit: "packs" },
            { name: "chicken broth", amount: 8, unit: "cups" },
            { name: "ginger", amount: 1, unit: "thumb-sized piece, grated" },
            { name: "soy sauce", amount: 1 / 4, unit: "cup" },
            { name: "mirin", amount: 1 / 4, unit: "cup" },
            { name: "cornstarch", amount: 2, unit: "tablespoons" },
            { name: "water", amount: 2, unit: "tablespoons" },
            { name: "pork cutlets", amount: 4, unit: "" },
            { name: "salt", amount: 1 / 2, unit: "teaspoon" },
            { name: "pepper", amount: 1 / 4, unit: "teaspoon" },
            { name: "flour", amount: 1 / 2, unit: "cup" },
            { name: "egg, beaten", amount: 2, unit: "" },
            { name: "panko breadcrumbs", amount: 2, unit: "cups" },
            { name: "vegetable oil", amount: 2, unit: "cups" },
            { name: "green onions, sliced", amount: 4, unit: "" },
            { name: "boiled egg, sliced", amount: 4, unit: "" },
        ],
        photo: "https://res.cloudinary.com/dfjboi5a7/image/upload/v1678652836/lxbrxaq92crqjfztpnqm.jpg",
        creator: creatorId,
    },
    {
        title: "Kung Pao Chicken",
        description:
            "A spicy and savory dish made with tender chicken, crunchy peanuts, and vegetables.",
        estimateTime: 30,
        servings: 4,
        steps: "1. Cut chicken into bite-size pieces and marinate with soy sauce and Shaoxing wine for 15 minutes. \n2. In a small bowl, mix cornstarch and water to make a slurry. \n3. In a wok or large skillet, heat oil over high heat. Add Sichuan peppercorns and stir-fry until fragrant. Remove and discard. \n4. Add chicken to the wok and stir-fry until no longer pink. Remove and set aside. \n5. Add garlic, ginger, and dried chili peppers to the wok and stir-fry until fragrant. \n6. Add vegetables (such as bell peppers, zucchini, or celery) and stir-fry for 1-2 minutes. \n7. Add peanuts, chicken, and sauce (made with soy sauce, vinegar, sugar, and chicken broth) to the wok. Stir-fry until the sauce thickens and coats the chicken and vegetables. \n8. Serve hot with steamed rice.",
        tips: "For a milder version, use fewer dried chili peppers or remove the seeds. You can also substitute chicken with other proteins, such as shrimp or tofu.",
        ingredients: [
            { name: "chicken breast", amount: 1, unit: "pound" },
            { name: "soy sauce", amount: 3, unit: "tablespoons" },
            { name: "Shaoxing wine", amount: 1, unit: "tablespoon" },
            { name: "cornstarch", amount: 1, unit: "tablespoon" },
            { name: "water", amount: 2, unit: "tablespoons" },
            { name: "vegetable oil", amount: 2, unit: "tablespoons" },
            { name: "Sichuan peppercorns", amount: 1, unit: "teaspoon" },
            { name: "garlic", amount: 3, unit: "cloves" },
            { name: "ginger", amount: 1, unit: "thumb-sized piece" },
            { name: "dried chili peppers", amount: 6, unit: "" },
            { name: "bell peppers", amount: 2, unit: "" },
            { name: "peanuts", amount: 1 / 2, unit: "cup" },
            { name: "soy sauce", amount: 2, unit: "tablespoons" },
            { name: "vinegar", amount: 1, unit: "tablespoon" },
            { name: "sugar", amount: 1, unit: "tablespoon" },
            { name: "chicken broth", amount: 1 / 4, unit: "cup" },
            { name: "steamed rice", amount: 4, unit: "servings" },
        ],
        photo: "https://res.cloudinary.com/dfjboi5a7/image/upload/v1678654198/tyson-XgA9PqVK0a8-unsplash_fqgfzx.jpg",
        creator: creatorId,
    },
    {
        title: "Moroccan Chicken Tagine",
        description:
            "A savory, slow-cooked stew with chicken, vegetables, and aromatic spices.",
        estimateTime: 120,
        servings: 6,
        steps: "1. In a large tagine or Dutch oven, heat olive oil over medium heat. \n2. Add chopped onions and garlic, and sauté until onions are translucent. \n3. Add chicken pieces and brown on both sides. \n4. Add chopped carrots, potatoes, and green bell peppers. \n5. Stir in canned diced tomatoes, chicken broth, and spices including ground ginger, ground cumin, ground cinnamon, and ground paprika. \n6. Reduce heat and simmer, covered, until chicken and vegetables are tender, about 1 1/2 hours. \n7. Serve hot, garnished with fresh cilantro leaves and a sprinkle of chopped almonds.",
        tips: "You can use chicken breasts, thighs, or a combination of both in this recipe. For a more authentic flavor, use preserved lemons instead of fresh lemons, and serve with couscous or flatbread.",
        ingredients: [
            { name: "olive oil", amount: 2, unit: "tablespoons" },
            { name: "onions", amount: 2, unit: "" },
            { name: "garlic", amount: 4, unit: "cloves" },
            { name: "chicken", amount: 2, unit: "pounds" },
            { name: "carrots", amount: 4, unit: "" },
            { name: "potatoes", amount: 2, unit: "" },
            { name: "green bell peppers", amount: 2, unit: "" },
            { name: "canned diced tomatoes", amount: 14, unit: "ounces" },
            { name: "chicken broth", amount: 2, unit: "cups" },
            { name: "ground ginger", amount: 1, unit: "teaspoon" },
            { name: "ground cumin", amount: 1, unit: "teaspoon" },
            { name: "ground cinnamon", amount: 1, unit: "teaspoon" },
            { name: "ground paprika", amount: 1, unit: "teaspoon" },
            { name: "salt", amount: 1, unit: "teaspoon" },
            { name: "black pepper", amount: 1 / 2, unit: "teaspoon" },
            { name: "fresh cilantro leaves", amount: 1 / 4, unit: "cup" },
            { name: "chopped almonds", amount: 1 / 4, unit: "cup" },
        ],
        photo: "https://res.cloudinary.com/dfjboi5a7/image/upload/v1678654167/ca-creative-cdVqG9vnCVw-unsplash_tr9voq.jpg",
        creator: creatorId,
    },
    {
        title: "Bibimbap",
        description:
            "A popular Korean rice bowl topped with various vegetables, meat, and egg.",
        estimateTime: 60,
        servings: 4,
        steps: "1. Rinse and cook the rice according to package directions. \n2. Cut the carrots, zucchini, and mushrooms into thin strips. \n3. Heat oil in a pan and stir-fry each vegetable separately until tender. \n4. Season each vegetable with salt and sesame oil. \n5. Cut the beef into thin strips and stir-fry in the same pan until cooked. Season with soy sauce and sugar. \n6. Fry 4 eggs over easy in a separate pan. \n7. To assemble, place a serving of rice in each bowl and arrange the vegetables, beef, and egg on top. \n8. Garnish with sliced scallions and serve with a dollop of gochujang sauce.",
        tips: "You can use any vegetables you have on hand. Bibimbap is also great with ground beef or tofu. Make sure to fry the egg over easy so that the yolk can mix in with the rice and other ingredients.",
        ingredients: [
            { name: "rice", amount: 2, unit: "cups" },
            { name: "carrots", amount: 2, unit: "" },
            { name: "zucchini", amount: 2, unit: "" },
            { name: "mushrooms", amount: 4, unit: "ounces" },
            { name: "beef sirloin", amount: 8, unit: "ounces" },
            { name: "soy sauce", amount: 1, unit: "tablespoon" },
            { name: "sugar", amount: 1, unit: "tablespoon" },
            { name: "salt", amount: 1 / 4, unit: "teaspoon" },
            { name: "sesame oil", amount: 1, unit: "teaspoon" },
            { name: "eggs", amount: 4, unit: "" },
            { name: "scallions", amount: 2, unit: "" },
            { name: "gochujang sauce", amount: 4, unit: "tablespoons" },
            { name: "vegetable oil", amount: 2, unit: "tablespoons" },
        ],
        photo: "https://res.cloudinary.com/dfjboi5a7/image/upload/v1678652857/xebi0d2a3rlrrqx9o9cw.jpg",
        creator: creatorId,
    },
    {
        title: "Thai Green Curry Chicken",
        description:
            "A delicious and fragrant Thai-style green curry chicken that's easy to make at home!",
        estimateTime: 45,
        servings: 4,
        steps: "1. In a large pot or wok, heat the oil over medium heat. \n2. Add the green curry paste and cook until fragrant. \n3. Add the chicken and stir until lightly browned. \n4. Add the coconut milk, sugar, fish sauce, and lime leaves, stirring to combine. \n5. Bring to a simmer and cook for 15-20 minutes, or until the chicken is cooked through. \n6. Add the Thai basil and stir to combine. \n7. Serve hot with rice.",
        tips: "For an extra kick of heat, add some chopped fresh chili peppers to the curry. You can also substitute the chicken with tofu or shrimp.",
        ingredients: [
            { name: "vegetable oil", amount: 2, unit: "tablespoons" },
            { name: "green curry paste", amount: 3, unit: "tablespoons" },
            { name: "chicken breasts", amount: 1, unit: "pound" },
            { name: "coconut milk", amount: 1, unit: "can" },
            { name: "palm sugar", amount: 2, unit: "tablespoons" },
            { name: "fish sauce", amount: 2, unit: "tablespoons" },
            { name: "lime leaves", amount: 4, unit: "" },
            { name: "Thai basil", amount: 1 / 2, unit: "cup" },
            { name: "rice", amount: 4, unit: "servings" },
        ],
        photo: "https://res.cloudinary.com/dfjboi5a7/image/upload/v1678654194/megan-bucknall-qav5LFLbSUk-unsplash_ljynik.jpg",
        creator: creatorId, 
    },
    {
        title: "Classic Cheeseburger",
        description:
            "A juicy and flavorful cheeseburger with all the classic toppings!",
        estimateTime: 30,
        servings: 4,
        steps: "1. Preheat grill to high heat. \n2. Season the ground beef with salt and pepper, then shape into 4 patties. \n3. Grill the patties for about 4-5 minutes on each side, or until desired level of doneness is reached. \n4. In the last minute of cooking, top each patty with a slice of cheese. \n5. Assemble the burger by placing a patty on the bottom half of the bun, followed by lettuce, tomato, onion, and any other desired toppings. \n6. Add ketchup, mustard, and/or mayo to the top half of the bun. \n7. Serve hot and enjoy!",
        tips: "For extra flavor, mix some Worcestershire sauce and minced garlic into the ground beef before shaping into patties. You can also toast the buns on the grill for added texture.",
        ingredients: [
            { name: "ground beef", amount: 1, unit: "pound" },
            { name: "salt", amount: 1 / 2, unit: "teaspoon" },
            { name: "black pepper", amount: 1 / 4, unit: "teaspoon" },
            { name: "cheddar cheese", amount: 4, unit: "slices" },
            { name: "burger buns", amount: 4, unit: "" },
            { name: "lettuce", amount: 4, unit: "leaves" },
            { name: "tomato", amount: 2, unit: "slices" },
            { name: "onion", amount: 4, unit: "slices" },
            { name: "ketchup", amount: 2, unit: "tablespoons" },
            { name: "mustard", amount: 1, unit: "tablespoon" },
            { name: "mayo", amount: 1, unit: "tablespoon" },
        ],
        photo: "https://res.cloudinary.com/dfjboi5a7/image/upload/v1678652812/xf5oymze8jpdny58qnwu.jpg",
        creator: creatorId,
    },
];
